<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="tests.khly6517.Khly6517Tests-20210915124557" tests="2" file="tests/khly6517.py" time="8.868" timestamp="2021-09-15T12:46:19" failures="1" errors="0" skipped="0">
	<testcase classname="tests.khly6517.Khly6517Tests" name="test_WHEN_set_pv_is_set_THEN_pv_updated_func" time="2.560" timestamp="2021-09-15T12:46:12" file="tests\khly6517.py" line="41"/>
	<testcase classname="tests.khly6517.Khly6517Tests" name="test_WHEN_set_pv_is_set_THEN_pv_updated_rang" time="6.307" timestamp="2021-09-15T12:46:19" file="tests\khly6517.py" line="45">
		<failure type="AssertionError" message="Expected PV, 'TE:NDW1798:KHLY6517_01:CURR:DC:RANG:SP' to have value '10' (type: 'str').
Final PV value was '10.0' (type: 'float')"><![CDATA[Traceback (most recent call last):
  File "C:\Instrument\Apps\EPICS\support\khly6517\master\system_tests\tests\khly6517.py", line 46, in test_WHEN_set_pv_is_set_THEN_pv_updated_rang
    self.set_and_check("CURR:DC:RANG:SP", "10", "CURR:DC:RANG", "10")
  File "C:\Instrument\Apps\EPICS\support\khly6517\master\system_tests\tests\khly6517.py", line 37, in set_and_check
    self.ca.assert_that_pv_is(setpointPVname, setpointPVvalue)
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 269, in assert_that_pv_is
    return self.assert_that_pv_value_causes_func_to_return_true(
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 248, in assert_that_pv_value_causes_func_to_return_true
    raise AssertionError(err)
AssertionError: Expected PV, 'TE:NDW1798:KHLY6517_01:CURR:DC:RANG:SP' to have value '10' (type: 'str').
Final PV value was '10.0' (type: 'float')
]]></failure>
	</testcase>
</testsuite>
