<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="tests.khly6517.Khly6517Tests-20210915134551" tests="1" file="tests/khly6517.py" time="6.214" timestamp="2021-09-15T13:46:10" failures="1" errors="0" skipped="0">
	<testcase classname="tests.khly6517.Khly6517Tests" name="test_WHEN_buttons_pressed_THEN_readings_read_from_device" time="6.214" timestamp="2021-09-15T13:46:10" file="tests\khly6517.py" line="117">
		<failure type="AssertionError" message="Expected PV, 'TE:NDW1798:KHLY6517_01:READ' to have value '0.25' (type: 'float').
Final PV value was '1.0' (type: 'float')"><![CDATA[Traceback (most recent call last):
  File "C:\Instrument\Apps\EPICS\support\khly6517\master\system_tests\tests\khly6517.py", line 134, in test_WHEN_buttons_pressed_THEN_readings_read_from_device
    self.button_and_check(test_answer_expected_volt[checkingOrder[i][0]], volt)
  File "C:\Instrument\Apps\EPICS\support\khly6517\master\system_tests\tests\khly6517.py", line 114, in button_and_check
    self.ca.assert_that_pv_is("READ", expectedReading)
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 269, in assert_that_pv_is
    return self.assert_that_pv_value_causes_func_to_return_true(
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 248, in assert_that_pv_value_causes_func_to_return_true
    raise AssertionError(err)
AssertionError: Expected PV, 'TE:NDW1798:KHLY6517_01:READ' to have value '0.25' (type: 'float').
Final PV value was '1.0' (type: 'float')
]]></failure>
		<system-out><![CDATA[checking: BTN:VOLT, val: 0

success

checking: BTN:VOLT, val: 0.25

]]></system-out>
	</testcase>
</testsuite>
